"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _PairType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _PairTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_PairType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    PAIR_TYPE_UNSPECIFIED: _PairType.ValueType  # 0
    PAIR_TYPE_LLM: _PairType.ValueType  # 1
    """LLM pair: chat_model_start + llm_end folded together."""
    PAIR_TYPE_TOOL: _PairType.ValueType  # 2
    """Tool pair: tool_start + tool_end folded together."""

class PairType(_PairType, metaclass=_PairTypeEnumTypeWrapper):
    """PairType identifies what an event pair represents."""

PAIR_TYPE_UNSPECIFIED: PairType.ValueType  # 0
PAIR_TYPE_LLM: PairType.ValueType  # 1
"""LLM pair: chat_model_start + llm_end folded together."""
PAIR_TYPE_TOOL: PairType.ValueType  # 2
"""Tool pair: tool_start + tool_end folded together."""
Global___PairType: _TypeAlias = PairType  # noqa: Y015

class _Mode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ModeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Mode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    MODE_UNSPECIFIED: _Mode.ValueType  # 0
    MODE_ALERT: _Mode.ValueType  # 1
    """Verdicts are dashboard-only, the server never pushes them to the SDK."""
    MODE_HITL: _Mode.ValueType  # 2
    """Server holds in-policy-scope verdicts pending dashboard approve/reject.
    Out-of-scope verdicts are forwarded immediately so the SDK doesn't stall.
    """
    MODE_BLOCK: _Mode.ValueType  # 3
    """Server forwards every verdict; the SDK enforces per the policy snapshot."""

class Mode(_Mode, metaclass=_ModeEnumTypeWrapper):
    """Mode of execution governs how the server handles verdicts for a session.
    Set via policies.mode and delivered to the SDK via PolicySnapshot
    on every Verdict.
    """

MODE_UNSPECIFIED: Mode.ValueType  # 0
MODE_ALERT: Mode.ValueType  # 1
"""Verdicts are dashboard-only, the server never pushes them to the SDK."""
MODE_HITL: Mode.ValueType  # 2
"""Server holds in-policy-scope verdicts pending dashboard approve/reject.
Out-of-scope verdicts are forwarded immediately so the SDK doesn't stall.
"""
MODE_BLOCK: Mode.ValueType  # 3
"""Server forwards every verdict; the SDK enforces per the policy snapshot."""
Global___Mode: _TypeAlias = Mode  # noqa: Y015

@_typing.final
class ChatMessage(_message.Message):
    """ChatMessage represents a conversation message with a string role."""

    DESCRIPTOR: _descriptor.Descriptor

    ROLE_FIELD_NUMBER: _builtins.int
    CONTENT_FIELD_NUMBER: _builtins.int
    role: _builtins.str
    """Role of this message (e.g. "system", "human", "ai", "tool")."""
    content: _builtins.str
    """Text content of the message."""
    def __init__(
        self,
        *,
        role: _builtins.str = ...,
        content: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["content", b"content", "role", b"role"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ChatMessage: _TypeAlias = ChatMessage  # noqa: Y015

@_typing.final
class ToolCall(_message.Message):
    """ToolCall represents a tool invocation the model decided to make."""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    ARGS_FIELD_NUMBER: _builtins.int
    ID_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """Tool name."""
    args: _builtins.str
    """JSON-encoded arguments object."""
    id: _builtins.str
    """Provider-assigned tool call ID (may be empty for non-LLM-originated tools)."""
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        args: _builtins.str = ...,
        id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["args", b"args", "id", b"id", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ToolCall: _TypeAlias = ToolCall  # noqa: Y015

@_typing.final
class TokenUsage(_message.Message):
    """TokenUsage holds token consumption counters."""

    DESCRIPTOR: _descriptor.Descriptor

    PROMPT_TOKENS_FIELD_NUMBER: _builtins.int
    COMPLETION_TOKENS_FIELD_NUMBER: _builtins.int
    TOTAL_TOKENS_FIELD_NUMBER: _builtins.int
    prompt_tokens: _builtins.int
    """Number of tokens in the prompt."""
    completion_tokens: _builtins.int
    """Number of tokens in the completion."""
    total_tokens: _builtins.int
    """Total tokens consumed."""
    def __init__(
        self,
        *,
        prompt_tokens: _builtins.int = ...,
        completion_tokens: _builtins.int = ...,
        total_tokens: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["completion_tokens", b"completion_tokens", "prompt_tokens", b"prompt_tokens", "total_tokens", b"total_tokens"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TokenUsage: _TypeAlias = TokenUsage  # noqa: Y015

@_typing.final
class AgentContext(_message.Message):
    """AgentContext carries the identity and prompts for an agent at a given
    point in the call stack.  An empty agent_id signals "no agent" and is
    used as the parent sentinel for top-level events.
    """

    DESCRIPTOR: _descriptor.Descriptor

    AGENT_ID_FIELD_NUMBER: _builtins.int
    SYSTEM_PROMPT_FIELD_NUMBER: _builtins.int
    USER_INSTRUCTION_FIELD_NUMBER: _builtins.int
    agent_id: _builtins.str
    """Opaque agent identifier derived from the framework's checkpoint
    namespace (e.g. "tools|reason").
    """
    system_prompt: _builtins.str
    """System prompt the agent is running under."""
    user_instruction: _builtins.str
    """User instruction driving the current invocation."""
    def __init__(
        self,
        *,
        agent_id: _builtins.str = ...,
        system_prompt: _builtins.str = ...,
        user_instruction: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["agent_id", b"agent_id", "system_prompt", b"system_prompt", "user_instruction", b"user_instruction"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AgentContext: _TypeAlias = AgentContext  # noqa: Y015

@_typing.final
class LlmPairData(_message.Message):
    """LlmPairData is the payload for PAIR_TYPE_LLM events: one chat_model_start
    folded with its matching llm_end.
    """

    DESCRIPTOR: _descriptor.Descriptor

    MODEL_FIELD_NUMBER: _builtins.int
    MESSAGES_FIELD_NUMBER: _builtins.int
    OUTPUT_FIELD_NUMBER: _builtins.int
    TOOL_CALLS_FIELD_NUMBER: _builtins.int
    USAGE_FIELD_NUMBER: _builtins.int
    model: _builtins.str
    """Model class name (e.g. "ChatAnthropic", "ChatOpenAI")."""
    output: _builtins.str
    """The model's text response."""
    @_builtins.property
    def messages(self) -> _containers.RepeatedCompositeFieldContainer[Global___ChatMessage]:
        """Ordered conversation messages sent to the model."""

    @_builtins.property
    def tool_calls(self) -> _containers.RepeatedCompositeFieldContainer[Global___ToolCall]:
        """Tool calls the model decided to make."""

    @_builtins.property
    def usage(self) -> Global___TokenUsage:
        """Token usage counters."""

    def __init__(
        self,
        *,
        model: _builtins.str = ...,
        messages: _abc.Iterable[Global___ChatMessage] | None = ...,
        output: _builtins.str = ...,
        tool_calls: _abc.Iterable[Global___ToolCall] | None = ...,
        usage: Global___TokenUsage | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["usage", b"usage"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["messages", b"messages", "model", b"model", "output", b"output", "tool_calls", b"tool_calls", "usage", b"usage"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LlmPairData: _TypeAlias = LlmPairData  # noqa: Y015

@_typing.final
class ToolPairData(_message.Message):
    """ToolPairData is the payload for PAIR_TYPE_TOOL events: one tool_start
    folded with its matching tool_end.
    """

    DESCRIPTOR: _descriptor.Descriptor

    TOOL_NAME_FIELD_NUMBER: _builtins.int
    TOOL_CALL_ID_FIELD_NUMBER: _builtins.int
    INPUT_FIELD_NUMBER: _builtins.int
    OUTPUT_FIELD_NUMBER: _builtins.int
    tool_name: _builtins.str
    """Name of the tool that was invoked."""
    tool_call_id: _builtins.str
    """ID linking this invocation to the model's tool call.  May be empty
    for tools invoked outside an LLM flow.
    """
    input: _builtins.str
    """JSON-encoded input passed to the tool."""
    output: _builtins.str
    """Tool execution output."""
    def __init__(
        self,
        *,
        tool_name: _builtins.str = ...,
        tool_call_id: _builtins.str = ...,
        input: _builtins.str = ...,
        output: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["input", b"input", "output", b"output", "tool_call_id", b"tool_call_id", "tool_name", b"tool_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ToolPairData: _TypeAlias = ToolPairData  # noqa: Y015

@_typing.final
class PairedEvent(_message.Message):
    """PairedEvent is a completed event pair with agent context attached."""

    DESCRIPTOR: _descriptor.Descriptor

    EVENT_ID_FIELD_NUMBER: _builtins.int
    INVOCATION_ID_FIELD_NUMBER: _builtins.int
    SESSION_ID_FIELD_NUMBER: _builtins.int
    RUN_ID_FIELD_NUMBER: _builtins.int
    PARENT_RUN_ID_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    PAIR_TYPE_FIELD_NUMBER: _builtins.int
    AGENT_FIELD_NUMBER: _builtins.int
    PARENT_FIELD_NUMBER: _builtins.int
    LLM_FIELD_NUMBER: _builtins.int
    TOOL_FIELD_NUMBER: _builtins.int
    METADATA_JSON_FIELD_NUMBER: _builtins.int
    event_id: _builtins.str
    """Unique event identifier."""
    invocation_id: _builtins.str
    """Groups all events for one user-prompted invocation of the top-level graph."""
    session_id: _builtins.str
    """Session identifier."""
    run_id: _builtins.str
    """Framework run ID for this pair (LLM run_id for LLM pairs, tool run_id for tool pairs)."""
    parent_run_id: _builtins.str
    """Parent run ID.  For tool pairs this points at the producing LLM's run_id
    and is the key used for block-mode verdict correlation.
    """
    timestamp: _builtins.str
    """ISO 8601 timestamp of the pair's completion (end event)."""
    pair_type: Global___PairType.ValueType
    """Whether this is an LLM pair or a tool pair."""
    metadata_json: _builtins.bytes
    """Escape hatch for framework metadata not modelled as first-class fields
    (e.g. LangGraph checkpoint_ns, arbitrary tags).
    """
    @_builtins.property
    def agent(self) -> Global___AgentContext:
        """The agent that produced this pair."""

    @_builtins.property
    def parent(self) -> Global___AgentContext:
        """The agent that delegated to this one.  agent_id == "" means top-level."""

    @_builtins.property
    def llm(self) -> Global___LlmPairData:
        """Payload for PAIR_TYPE_LLM."""

    @_builtins.property
    def tool(self) -> Global___ToolPairData:
        """Payload for PAIR_TYPE_TOOL."""

    def __init__(
        self,
        *,
        event_id: _builtins.str = ...,
        invocation_id: _builtins.str = ...,
        session_id: _builtins.str = ...,
        run_id: _builtins.str = ...,
        parent_run_id: _builtins.str = ...,
        timestamp: _builtins.str = ...,
        pair_type: Global___PairType.ValueType = ...,
        agent: Global___AgentContext | None = ...,
        parent: Global___AgentContext | None = ...,
        llm: Global___LlmPairData | None = ...,
        tool: Global___ToolPairData | None = ...,
        metadata_json: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["agent", b"agent", "data", b"data", "llm", b"llm", "parent", b"parent", "tool", b"tool"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["agent", b"agent", "data", b"data", "event_id", b"event_id", "invocation_id", b"invocation_id", "llm", b"llm", "metadata_json", b"metadata_json", "pair_type", b"pair_type", "parent", b"parent", "parent_run_id", b"parent_run_id", "run_id", b"run_id", "session_id", b"session_id", "timestamp", b"timestamp", "tool", b"tool"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_data: _TypeAlias = _typing.Literal["llm", "tool"]  # noqa: Y015
    _WhichOneofArgType_data: _TypeAlias = _typing.Literal["data", b"data"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_data) -> _WhichOneofReturnType_data | None: ...

Global___PairedEvent: _TypeAlias = PairedEvent  # noqa: Y015

@_typing.final
class PairedEventBatch(_message.Message):
    """PairedEventBatch wraps multiple paired events for batched WebSocket frames."""

    DESCRIPTOR: _descriptor.Descriptor

    EVENTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def events(self) -> _containers.RepeatedCompositeFieldContainer[Global___PairedEvent]: ...
    def __init__(
        self,
        *,
        events: _abc.Iterable[Global___PairedEvent] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["events", b"events"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PairedEventBatch: _TypeAlias = PairedEventBatch  # noqa: Y015

@_typing.final
class McpServer(_message.Message):
    """McpServer is one MCP server the SDK observed at startup. Mirrors the
    SDK-side McpServer dataclass.
    """

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    TRANSPORT_FIELD_NUMBER: _builtins.int
    ENDPOINT_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """Server identifier. Adapter-layer captures use the connection key
    from MultiServerMCPClient.connections; raw-transport captures
    synthesise "<transport>:<endpoint>".
    """
    transport: _builtins.str
    """One of "stdio", "sse", "streamable_http", "websocket", or "unknown"."""
    endpoint: _builtins.str
    """URL for SSE/HTTP/WebSocket transports, or the joined command line
    for stdio. Empty string when neither is available.
    """
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        transport: _builtins.str = ...,
        endpoint: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["endpoint", b"endpoint", "name", b"name", "transport", b"transport"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___McpServer: _TypeAlias = McpServer  # noqa: Y015

@_typing.final
class McpInventory(_message.Message):
    """McpInventory is the SDK's one-shot dump of its connected MCP servers.
    Sent once per WS session right after the SDK login. The server replaces
    the session's entire MCP-server list on receipt, no diff/merge.
    """

    DESCRIPTOR: _descriptor.Descriptor

    SERVERS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def servers(self) -> _containers.RepeatedCompositeFieldContainer[Global___McpServer]: ...
    def __init__(
        self,
        *,
        servers: _abc.Iterable[Global___McpServer] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["servers", b"servers"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___McpInventory: _TypeAlias = McpInventory  # noqa: Y015

@_typing.final
class LLMStack(_message.Message):
    """LLMStack identifies the LLM provider and model for a session."""

    DESCRIPTOR: _descriptor.Descriptor

    PROVIDER_FIELD_NUMBER: _builtins.int
    MODEL_FIELD_NUMBER: _builtins.int
    provider: _builtins.str
    """Provider name (e.g. "anthropic", "openai")."""
    model: _builtins.str
    """Model identifier (e.g. "claude-sonnet-4-20250514")."""
    def __init__(
        self,
        *,
        provider: _builtins.str = ...,
        model: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["model", b"model", "provider", b"provider"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LLMStack: _TypeAlias = LLMStack  # noqa: Y015

@_typing.final
class SessionLogin(_message.Message):
    """SessionLogin is sent as the first frame after WebSocket upgrade."""

    DESCRIPTOR: _descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: _builtins.int
    LLM_STACK_FIELD_NUMBER: _builtins.int
    SCHEMA_VERSION_FIELD_NUMBER: _builtins.int
    session_id: _builtins.str
    """Session identifier."""
    schema_version: _builtins.int
    """Wire schema version the client is speaking.  Server rejects unknown values."""
    @_builtins.property
    def llm_stack(self) -> Global___LLMStack:
        """LLM stack information for this session."""

    def __init__(
        self,
        *,
        session_id: _builtins.str = ...,
        llm_stack: Global___LLMStack | None = ...,
        schema_version: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["llm_stack", b"llm_stack"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["llm_stack", b"llm_stack", "schema_version", b"schema_version", "session_id", b"session_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SessionLogin: _TypeAlias = SessionLogin  # noqa: Y015

@_typing.final
class ClientFrame(_message.Message):
    """ClientFrame is the top-level envelope for all client WebSocket messages."""

    DESCRIPTOR: _descriptor.Descriptor

    LOGIN_FIELD_NUMBER: _builtins.int
    PAIRED_BATCH_FIELD_NUMBER: _builtins.int
    MCP_INVENTORY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def login(self) -> Global___SessionLogin:
        """Session login (must be first frame)."""

    @_builtins.property
    def paired_batch(self) -> Global___PairedEventBatch:
        """Paired event batch (requires prior login)."""

    @_builtins.property
    def mcp_inventory(self) -> Global___McpInventory:
        """One-shot MCP-server inventory dump from the SDK after login."""

    def __init__(
        self,
        *,
        login: Global___SessionLogin | None = ...,
        paired_batch: Global___PairedEventBatch | None = ...,
        mcp_inventory: Global___McpInventory | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["frame", b"frame", "login", b"login", "mcp_inventory", b"mcp_inventory", "paired_batch", b"paired_batch"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["frame", b"frame", "login", b"login", "mcp_inventory", b"mcp_inventory", "paired_batch", b"paired_batch"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_frame: _TypeAlias = _typing.Literal["login", "paired_batch", "mcp_inventory"]  # noqa: Y015
    _WhichOneofArgType_frame: _TypeAlias = _typing.Literal["frame", b"frame"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_frame) -> _WhichOneofReturnType_frame | None: ...

Global___ClientFrame: _TypeAlias = ClientFrame  # noqa: Y015

@_typing.final
class PolicySnapshot(_message.Message):
    """PolicySnapshot is the org's effective execution-mode policy at the moment
    a verdict was decided. Attached by the server to every Verdict it sends
    so the SDK can apply user-configured behaviour (halt vs continue,
    review-pending vs proceed) without an extra round-trip to fetch policy.

    Per-MAD-code booleans say whether the active mode's behaviour fires on
    that code. False means "treat this code as silent regardless of mode".
    """

    DESCRIPTOR: _descriptor.Descriptor

    MODE_FIELD_NUMBER: _builtins.int
    POLICY_M0_FIELD_NUMBER: _builtins.int
    POLICY_M2_FIELD_NUMBER: _builtins.int
    POLICY_M3_FIELD_NUMBER: _builtins.int
    POLICY_M4_FIELD_NUMBER: _builtins.int
    mode: Global___Mode.ValueType
    policy_m0: _builtins.bool
    policy_m2: _builtins.bool
    policy_m3: _builtins.bool
    policy_m4: _builtins.bool
    def __init__(
        self,
        *,
        mode: Global___Mode.ValueType = ...,
        policy_m0: _builtins.bool = ...,
        policy_m2: _builtins.bool = ...,
        policy_m3: _builtins.bool = ...,
        policy_m4: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["mode", b"mode", "policy_m0", b"policy_m0", "policy_m2", b"policy_m2", "policy_m3", b"policy_m3", "policy_m4", b"policy_m4"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PolicySnapshot: _TypeAlias = PolicySnapshot  # noqa: Y015

@_typing.final
class HitlResponse(_message.Message):
    """HitlResponse rides on a Verdict that has been resolved through the
    human-in-the-loop review queue. Absent on regular (non-HITL or
    out-of-scope) verdicts.
    """

    DESCRIPTOR: _descriptor.Descriptor

    CONTINUE_EXECUTION_FIELD_NUMBER: _builtins.int
    continue_execution: _builtins.bool
    """True if the reviewer approved (agent should continue), false if rejected."""
    def __init__(
        self,
        *,
        continue_execution: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["continue_execution", b"continue_execution"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___HitlResponse: _TypeAlias = HitlResponse  # noqa: Y015

@_typing.final
class LoginAck(_message.Message):
    """LoginAck is the server's first frame after a successful SessionLogin.
    Carries the org's effective policy so the SDK can apply correct mode +
    timeout behaviour from the very first event, before any verdict round-trip.

    Policy snapshot is captured at WS login time. Mid-session policy changes
    do NOT propagate to existing sessions, reconnect for new policy to take
    effect.
    """

    DESCRIPTOR: _descriptor.Descriptor

    POLICY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def policy(self) -> Global___PolicySnapshot: ...
    def __init__(
        self,
        *,
        policy: Global___PolicySnapshot | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["policy", b"policy"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["policy", b"policy"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LoginAck: _TypeAlias = LoginAck  # noqa: Y015

@_typing.final
class ServerFrame(_message.Message):
    """ServerFrame is the top-level envelope for all server→SDK WebSocket
    messages. Multiplexes login-ack, verdicts, and any future server-pushed
    frame types over the same WebSocket without ambiguity.
    """

    DESCRIPTOR: _descriptor.Descriptor

    LOGIN_ACK_FIELD_NUMBER: _builtins.int
    VERDICT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def login_ack(self) -> Global___LoginAck:
        """Sent exactly once, immediately after a successful SessionLogin."""

    @_builtins.property
    def verdict(self) -> Global___Verdict:
        """Sent for every classified event the server forwards to the SDK
        (subject to mode/policy gates).
        """

    def __init__(
        self,
        *,
        login_ack: Global___LoginAck | None = ...,
        verdict: Global___Verdict | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["frame", b"frame", "login_ack", b"login_ack", "verdict", b"verdict"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["frame", b"frame", "login_ack", b"login_ack", "verdict", b"verdict"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_frame: _TypeAlias = _typing.Literal["login_ack", "verdict"]  # noqa: Y015
    _WhichOneofArgType_frame: _TypeAlias = _typing.Literal["frame", b"frame"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_frame) -> _WhichOneofReturnType_frame | None: ...

Global___ServerFrame: _TypeAlias = ServerFrame  # noqa: Y015

@_typing.final
class Verdict(_message.Message):
    """Verdict is the classification result for a PairedEvent."""

    DESCRIPTOR: _descriptor.Descriptor

    EVENT_ID_FIELD_NUMBER: _builtins.int
    SESSION_ID_FIELD_NUMBER: _builtins.int
    MAD_CODE_FIELD_NUMBER: _builtins.int
    POLICY_FIELD_NUMBER: _builtins.int
    HITL_FIELD_NUMBER: _builtins.int
    event_id: _builtins.str
    """The event_id of the PairedEvent being classified."""
    session_id: _builtins.str
    """Session identifier for routing."""
    mad_code: _builtins.str
    """MAD code the classifier returned (e.g. "M0", "M2_C", "M4_a").  Empty string for benign."""
    @_builtins.property
    def policy(self) -> Global___PolicySnapshot:
        """Org's effective execution-mode policy at the time of this verdict.
        Always populated by the server; SDK reads this to decide whether to
        halt, pause, or continue.
        """

    @_builtins.property
    def hitl(self) -> Global___HitlResponse:
        """Present only when this verdict represents a human-in-the-loop review
        resolution (approve or reject from the dashboard). Absent on auto-
        classified verdicts and on out-of-scope verdicts forwarded immediately.
        """

    def __init__(
        self,
        *,
        event_id: _builtins.str = ...,
        session_id: _builtins.str = ...,
        mad_code: _builtins.str = ...,
        policy: Global___PolicySnapshot | None = ...,
        hitl: Global___HitlResponse | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["hitl", b"hitl", "policy", b"policy"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["event_id", b"event_id", "hitl", b"hitl", "mad_code", b"mad_code", "policy", b"policy", "session_id", b"session_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Verdict: _TypeAlias = Verdict  # noqa: Y015
